# Generated by Django 4.1.7 on 2023-03-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_customer_alter_productreview_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Womens', 'Womens'), ('Kids', 'Kids'), ('Electronics', 'Electronics'), ('Beauty', 'Beauty'), ('HD', 'HD')], max_length=20),
        ),
    ]
