# Generated by Django 4.1.7 on 2023-07-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_date_joined_customer_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=30),
        ),
    ]
